# Association :-
- ##### We find similarity of samples with all other samples.
- ##### Generally cosine similarity is used for this score.
- ##### Recommendation System is the best example of Association.

In [1]:
s1="python is a programming language"
s2="rohit sharma is a cricketer"
s3="java is also a programming language"

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
tfv=TfidfVectorizer()
matrix=tfv.fit_transform([s1,s2,s3]).toarray()
matrix

array([[0.        , 0.        , 0.37311881, 0.        , 0.4804584 ,
        0.4804584 , 0.63174505, 0.        , 0.        ],
       [0.        , 0.54645401, 0.32274454, 0.        , 0.        ,
        0.        , 0.        , 0.54645401, 0.54645401],
       [0.53409337, 0.        , 0.31544415, 0.53409337, 0.40619178,
        0.40619178, 0.        , 0.        , 0.        ]])

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

In [5]:
cosine_similarity(matrix)

array([[1.        , 0.12042206, 0.50801465],
       [0.12042206, 1.        , 0.10180788],
       [0.50801465, 0.10180788, 1.        ]])

In [6]:
from sklearn.metrics.pairwise import cosine_distances

In [7]:
cosine_distances(matrix)

array([[0.        , 0.87957794, 0.49198535],
       [0.87957794, 0.        , 0.89819212],
       [0.49198535, 0.89819212, 0.        ]])

# Content Based Recommendation System :-

In [8]:
import pandas as pd

In [9]:
df=pd.read_csv('movies_content.csv')

df

movie_id                                        description  \
0     tt5286444  Neerja is the story of the courageous Neerja B...   
1     tt4434004  A story that revolves around drug abuse in the...   
2     tt0248126  Yashvardhan Raichand lives a very wealthy life...   
3     tt0347304  Naina, an introverted, perpetually depressed g...   
4     tt3043252  'Parched' is a story about women set in the he...   
...         ...                                                ...   
2845  tt0308793                                                NaN   
2846  tt3006508                                                NaN   
2847  tt5348692  The plot is simple. Ranganna (Rangayana Raghu)...   
2848  tt3171754                                                NaN   
2849  tt0231455                                                NaN   

                                        language                  released  \
0                                    [ "Hindi" ]  2016-02-19T00:00:00.000Z   
1                         [ "Hindi", "Panjabi" ]  2016-06-17T00:00:00.000Z   
2                 [ "Hindi", "English", "Urdu" ]  2001-12-14T00:00:00.000Z   
3     [ "Hindi", "Urdu", "Gujarati", "Panjabi" ]  2003-11-28T00:00:00.000Z   
4                         [ "Hindi", "English" ]  2016-06-17T00:00:00.000Z   
...                                          ...                       ...   
2845                               [ "Kannada" ]                       NaN   
2846                               [ "Kannada" ]                2013-02-22   
2847                               [ "Kannada" ]                2013-11-29   
2848                               [ "Kannada" ]                2013-12-27   
2849                               [ "Kannada" ]                       NaN   

      rating                                          writer  \
0        7.9  [ "Saiwyn Quadras", "Sanyukta Shaikh Chawla" ]   
1        7.9          [ "Sudip Sharma", "Abhishek Chaubey" ]   
2        7.5              [ "Karan Johar", "Sheena Parikh" ]   
3        8.0           [ "Niranjan Iyengar", "Karan Johar" ]   
4        7.6               [ "Supratik Sen", "Leena Yadav" ]   
...      ...                                             ...   
2845     7.7                                              []   
2846     7.7                                              []   
2847     7.7                                [ "Pc Shekhar" ]   
2848     7.6                                              []   
2849     7.5                                              []   

                        director  \
0             [ "Ram Madhvani" ]   
1         [ "Abhishek Chaubey" ]   
2              [ "Karan Johar" ]   
3           [ "Nikkhil Advani" ]   
4              [ "Leena Yadav" ]   
...                          ...   
2845       [ "V. Ravichandran" ]   
2846            [ "Nagashekar" ]   
2847            [ "Pc Shekhar" ]   
2848          [ "Manju Swaraj" ]   
2849  [ "S.R. Puttana Kanagal" ]   

                                                   cast  \
0     [ "Sonam Kapoor", "Shabana Azmi", "Yogendra Ti...   
1     [ "Alia Bhatt", "Shahid Kapoor", "Diljit Dosan...   
2     [ "Amitabh Bachchan", "Jaya Bhaduri", "Shah Ru...   
3     [ "Shah Rukh Khan", "Preity Zinta", "Saif Ali ...   
4     [ "Tannishtha Chatterjee", "Radhika Apte", "Le...   
...                                                 ...   
2845  [ "V. Ravichandran", "Kushboo", "Anant Nag", "...   
2846  [ "Chethan Kumar", "Nithya Menon", "Sarath Kum...   
2847   [ "Rangayana Raghu", "Sadhu Kokila", "Avinash" ]   
2848  [ "Ganesh", "Amulya", "Anant Nag", "Tara", "Av...   
2849                                                 []   

                                     genre                         name  
0     [ "Biography", "Drama", "Thriller" ]                       Neerja  
1         [ "Crime", "Drama", "Thriller" ]                  Udta Punjab  
2        [ "Drama", "Musical", "Romance" ]  Kabhi Khushi Kabhie Gham...  
3         [ "Comedy", 

In [10]:
df=df[['name','description']]
df

name  \
0                          Neerja   
1                     Udta Punjab   
2     Kabhi Khushi Kabhie Gham...   
3                   Kal Ho Naa Ho   
4                         Parched   
...                           ...   
2845                   Ranadheera   
2846                         Myna   
2847                 Chaddi Dosth   
2848          Shravani Subramanya   
2849                   Dharmasere   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
2845                                                NaN  
2846                                                NaN  
2847  The plot is simple. Ranganna (Rangayana Raghu)...  
2848                                                NaN  
2849                                                NaN  

[2850 rows x 2 columns]

In [11]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df

name  \
0                          Neerja   
1                     Udta Punjab   
2     Kabhi Khushi Kabhie Gham...   
3                   Kal Ho Naa Ho   
4                         Parched   
...                           ...   
2845                   Ranadheera   
2846                         Myna   
2847                 Chaddi Dosth   
2848          Shravani Subramanya   
2849                   Dharmasere   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
2845                                                NaN  
2846                                                NaN  
2847  The plot is simple. Ranganna (Rangayana Raghu)...  
2848                                                NaN  
2849                                                NaN  

[2837 rows x 2 columns]

In [14]:
df.dropna(inplace=True)

In [15]:
df

name  \
0                           Neerja   
1                      Udta Punjab   
2      Kabhi Khushi Kabhie Gham...   
3                    Kal Ho Naa Ho   
4                          Parched   
...                            ...   
2838                    Run Antony   
2841                    Jolly Days   
2842  The Great Story of Sodabuddi   
2844                        Vamshi   
2847                  Chaddi Dosth   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
2838  Antony is depressed and wants to commit suicid...  
2841  A bubbly tale, the story is about four pairs o...  
2842  The film tells the story of Sodabuddi, who spe...  
2844  Vamshi, under the eye of his mother is living ...  
2847  The plot is simple. Ranganna (Rangayana Raghu)...  

[1751 rows x 2 columns]

In [16]:
df.reset_index()

index                          name  \
0         0                        Neerja   
1         1                   Udta Punjab   
2         2   Kabhi Khushi Kabhie Gham...   
3         3                 Kal Ho Naa Ho   
4         4                       Parched   
...     ...                           ...   
1746   2838                    Run Antony   
1747   2841                    Jolly Days   
1748   2842  The Great Story of Sodabuddi   
1749   2844                        Vamshi   
1750   2847                  Chaddi Dosth   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
1746  Antony is depressed and wants to commit suicid...  
1747  A bubbly tale, the story is about four pairs o...  
1748  The film tells the story of Sodabuddi, who spe...  
1749  Vamshi, under the eye of his mother is living ...  
1750  The plot is simple. Ranganna (Rangayana Raghu)...  

[1751 rows x 3 columns]

In [17]:
df.reset_index(drop=True,inplace=True)
df

name  \
0                           Neerja   
1                      Udta Punjab   
2      Kabhi Khushi Kabhie Gham...   
3                    Kal Ho Naa Ho   
4                          Parched   
...                            ...   
1746                    Run Antony   
1747                    Jolly Days   
1748  The Great Story of Sodabuddi   
1749                        Vamshi   
1750                  Chaddi Dosth   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
1746  Antony is depressed and wants to commit suicid...  
1747  A bubbly tale, the story is about four pairs o...  
1748  The film tells the story of Sodabuddi, who spe...  
1749  Vamshi, under the eye of his mother is living ...  
1750  The plot is simple. Ranganna (Rangayana Raghu)...  

[1751 rows x 2 columns]

In [18]:
df.name=df.name.map(str.lower)
df

name  \
0                           neerja   
1                      udta punjab   
2      kabhi khushi kabhie gham...   
3                    kal ho naa ho   
4                          parched   
...                            ...   
1746                    run antony   
1747                    jolly days   
1748  the great story of sodabuddi   
1749                        vamshi   
1750                  chaddi dosth   

                                            description  
0     Neerja is the story of the courageous Neerja B...  
1     A story that revolves around drug abuse in the...  
2     Yashvardhan Raichand lives a very wealthy life...  
3     Naina, an introverted, perpetually depressed g...  
4     'Parched' is a story about women set in the he...  
...                                                 ...  
1746  Antony is depressed and wants to commit suicid...  
1747  A bubbly tale, the story is about four pairs o...  
1748  The film tells the story of Sodabuddi, who spe...  
1749  Vamshi, under the eye of his mother is living ...  
1750  The plot is simple. Ranganna (Rangayana Raghu)...  

[1751 rows x 2 columns]

In [19]:
tfv=TfidfVectorizer()
matrix=tfv.fit_transform(df.description).toarray()

In [20]:
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1751, 7957))

In [21]:
from sklearn.neighbors import NearestNeighbors

In [22]:
model=NearestNeighbors(metric='cosine') #cosine distances
model.fit(matrix)

NearestNeighbors(metric='cosine')

In [23]:
mv='Udta Punjab'.lower()
mi=df[df.name==mv].index[0]

In [24]:
mi

np.int64(1)

In [25]:
matrix[mi]

array([0., 0., 0., ..., 0., 0., 0.], shape=(7957,))

In [26]:
dis,idx=model.kneighbors([matrix[mi]],n_neighbors=5)

In [27]:
dis

array([[0.        , 0.82848389, 0.86335549, 0.86364972, 0.87154048]])

In [28]:
idx

array([[  1, 862, 860, 940, 280]])

In [29]:
idx[0]

array([  1, 862, 860, 940, 280])

In [30]:
for i in idx[0][1:]:
    print(i)

862
860
940
280


In [31]:
for i in idx[0][1:]:
    print(df.loc[i].values[0])

ardaas
gelo
shareek
maachis


In [33]:
df=pd.read_csv('movies_content.csv')
df=df[['name','description']]
df.drop_duplicates(inplace=True)
df.dropna(inplace=True)
df.reset_index(drop=True,inplace=True)
df.name=df.name.map(str.lower)
tfv=TfidfVectorizer()
matrix=tfv.fit_transform(df.description).toarray()
model=NearestNeighbors(metric='cosine') #cosine distances
model.fit(matrix)

NearestNeighbors(metric='cosine')

In [34]:
try:
    mv=input('Enter Movie Name:').lower()
    mi=df[df.name==mv].index[0]
    dis,idx=model.kneighbors([matrix[mi]],n_neighbors=5)
    print("*********Recommendations for you********")
    for i in idx[0][1:]:
        print(df.loc[i].values[0])
except:
    print("something went wrong,might be due movie not found in database")

Enter Movie Name: histry


something went wrong,might be due movie not found in database
