In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('carprices.csv')
df.head()

Car Model  Mileage  Sell Price($)  Age(yrs)
0    BMW X5    69000          18000         6
1    BMW X5    35000          34000         3
2    BMW X5    57000          26100         5
3    BMW X5    22500          40000         2
4    BMW X5    46000          31500         4

In [3]:
df.dropna(subset=['Age(yrs)'],inplace=True)

In [4]:
from sklearn.impute import SimpleImputer

In [5]:
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
imp

SimpleImputer()

In [6]:
x=df.iloc[:,:-1]
y=df.iloc[:,3]

In [7]:
x.iloc[:,1:3]=imp.fit_transform(x.iloc[:,1:3])

In [8]:
x.shape

(26, 3)

In [9]:
dic={'Car Model':str,'Mileage':int,'Sell Price($)':int}
dic

{'Car Model': str, 'Mileage': int, 'Sell Price($)': int}

In [10]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [12]:
one=OneHotEncoder(sparse_output=False,dtype=int).set_output(transform='pandas')

In [13]:
One_transform=one.fit_transform([['Car Model']])

In [14]:
x=pd.concat([x,One_transform],axis=1).drop(columns=['Car Model'])

In [16]:
label_y=LabelEncoder()
y=label_y.fit_transform(y)
y

array([4, 1, 3, 0, 2, 3, 3, 4, 6, 4, 5, 5, 3, 4, 1, 3, 0, 2, 3, 3, 4, 6,
       4, 5, 5, 3])

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
sc=StandardScaler()

In [19]:
x1=x.iloc[:,0:2]
x1

Mileage  Sell Price($)
0     69000          18000
1     35000          34000
2     57000          26100
3     22500          40000
4     46000          31500
5     59000          29400
6     52000          32000
7     72000          19300
8     91000          12000
9     67000          22000
10    83000          20000
11    79000          21000
12    59000          33000
13    69000          18000
14    35000          34000
15    57000          26100
16    22500          40000
17    46000          31500
18    59000          29400
19    52000          32000
20    72000          19300
21    91000          12000
22    67000          22000
23    83000          20000
24    79000          21000
25    59000          33000

In [20]:
x_new=sc.fit_transform(x1)
x_new

array([[ 0.44026413, -1.04335793],
       [-1.40425478,  1.03735587],
       [-0.21074255,  0.01000343],
       [-2.08238673,  1.81762355],
       [-0.80749866,  0.71224434],
       [-0.10224143,  0.43915065],
       [-0.48199533,  0.77726665],
       [ 0.6030158 , -0.87429994],
       [ 1.63377636, -1.82362561],
       [ 0.33176302, -0.52317948],
       [ 1.19977192, -0.78326871],
       [ 0.98276969, -0.65322409],
       [-0.10224143,  0.90731126],
       [ 0.44026413, -1.04335793],
       [-1.40425478,  1.03735587],
       [-0.21074255,  0.01000343],
       [-2.08238673,  1.81762355],
       [-0.80749866,  0.71224434],
       [-0.10224143,  0.43915065],
       [-0.48199533,  0.77726665],
       [ 0.6030158 , -0.87429994],
       [ 1.63377636, -1.82362561],
       [ 0.33176302, -0.52317948],
       [ 1.19977192, -0.78326871],
       [ 0.98276969, -0.65322409],
       [-0.10224143,  0.90731126]])

In [21]:
x_new=pd.DataFrame(x_new,columns=['Mileage','Sell Price($)'])

In [26]:
x_new=pd.get_dummies(x['Mileage'])
x_combadea=pd.concat([x.iloc[:,2:],x_new],axis='columns')

In [27]:
merged=pd.concat([x.iloc[:,2:],x_new],axis='columns')
merged

x0_Car Model  22500  35000  46000  52000  57000  59000  67000  69000  \
0            1.0  False  False  False  False  False  False  False   True   
1            NaN  False   True  False  False  False  False  False  False   
2            NaN  False  False  False  False   True  False  False  False   
3            NaN   True  False  False  False  False  False  False  False   
4            NaN  False  False   True  False  False  False  False  False   
5            NaN  False  False  False  False  False   True  False  False   
6            NaN  False  False  False   True  False  False  False  False   
7            NaN  False  False  False  False  False  False  False  False   
8            NaN  False  False  False  False  False  False  False  False   
9            NaN  False  False  False  False  False  False   True  False   
10           NaN  False  False  False  False  False  False  False  False   
11           NaN  False  False  False  False  False  False  False  False   
12           NaN  False  False  False  False  False   True  False  False   
13           NaN  False  False  False  False  False  False  False   True   
14           NaN  False   True  False  False  False  False  False  False   
15           NaN  False  False  False  False   True  False  False  False   
16           NaN   True  False  False  False  False  False  False  False   
17           NaN  False  False   True  False  False  False  False  False   
18           NaN  False  False  False  False  False   True  False  False   
19           NaN  False  False  False   True  False  False  False  False   
20           NaN  False  False  False  False  False  False  False  False   
21           NaN  False  False  False  False  False  False  False  False   
22           NaN  False  False  False  False  False  False   True  False   
23           NaN  False  False  False  False  False  False  False  False   
24           NaN  False  False  False  False  False  False  False  False   
25           NaN  False  False  False  False  False   True  False  False   

    72000  79000  83000  91000  
0   False  False  False  False  
1   False  False  False  False  
2   False  False  False  False  
3   False  False  False  False  
4   False  False  False  False  
5   False  False  False  False  
6   False  False  False  False  
7    True  False  False  False  
8   False  False  False   True  
9   False  False  False  False  
10  False  False   True  False  
11  False   True  False  False  
12  False  False  False  False  
13  False  False  False  False  
14  False  False  False  False  
15  False  False  False  False  
16  False  False  False  False  
17  False  False  False  False  
18  False  False  False  False  
19  False  False  False  False  
20   True  False  False  False  
21  False  False  False   True  
22  False  False  False  False  
23  False  False   True  False  
24  False   True  False  False  
25  False  False  False  False

In [33]:
from sklearn.preprocessing import MinMaxScaler

In [34]:
sc = MinMaxScaler(feature_range=(0, 1))

In [38]:
x1 = x.iloc[:, 0:2]

In [39]:
x_new = sc.fit_transform(x1)

In [40]:
x_new

array([[0.67883212, 0.21428571],
       [0.18248175, 0.78571429],
       [0.50364964, 0.50357143],
       [0.        , 1.        ],
       [0.34306569, 0.69642857],
       [0.53284672, 0.62142857],
       [0.43065693, 0.71428571],
       [0.72262774, 0.26071429],
       [1.        , 0.        ],
       [0.64963504, 0.35714286],
       [0.88321168, 0.28571429],
       [0.82481752, 0.32142857],
       [0.53284672, 0.75      ],
       [0.67883212, 0.21428571],
       [0.18248175, 0.78571429],
       [0.50364964, 0.50357143],
       [0.        , 1.        ],
       [0.34306569, 0.69642857],
       [0.53284672, 0.62142857],
       [0.43065693, 0.71428571],
       [0.72262774, 0.26071429],
       [1.        , 0.        ],
       [0.64963504, 0.35714286],
       [0.88321168, 0.28571429],
       [0.82481752, 0.32142857],
       [0.53284672, 0.75      ]])