In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
x=iris.data
y=iris.target

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
model=LogisticRegression(multi_class='ovr')
model.fit(x,y)

C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [6]:
sample=[1.5,.8,3.5,.9]
print(model.predict_proba([sample]))
print(model.predict([sample]))

[[0.08312302 0.87525322 0.04162376]]
[1]


In [7]:
model.coef_

array([[-0.44565052,  0.90054581, -2.32023343, -0.98112874],
       [-0.17917535, -2.12878487,  0.69671839, -1.27500517],
       [-0.39270716, -0.51442952,  2.93064063,  2.41608802]])

In [8]:
model.intercept_

array([  6.68931554,   5.58592907, -14.43598319])

In [12]:
z0=-0.44565052*1.5+0.90054581*.8+-2.32023343*3.5+-0.98112874*.9+6.68931554
z1=-0.17917535*1.5+-2.12878487*.8+0.69671839*3.5+ -1.27500517*.9+5.58592907
z2=-0.39270716*1.5+-0.51442952*.8+ 2.93064063*3.5+2.41608802*.9+-14.43598319

In [13]:
print(z0,z1,z2)

-2.2625564629999984 4.905147861 -3.0048661229999993


In [14]:
model.decision_function([sample])

array([[-2.26255646,  4.90514787, -3.00486612]])

In [15]:
import numpy as np

In [18]:
p0=1/(1+np.exp(-z0))
p1=1/(1+np.exp(-z1))
p2=1/(1+np.exp(-z2))

In [19]:
print(p0,p1,p2)

0.09427185965968823 0.9926461324110328 0.047206521501534475


In [20]:
model.predict_proba([sample])

array([[0.08312302, 0.87525322, 0.04162376]])

In [21]:
pn0=p0/(p0+p1+p2)
pn1=p1/(p0+p1+p2)
pn2=p2/(p0+p1+p2)
print(pn0,pn1,pn2)

0.08312302444001633 0.8752532200229097 0.04162375553707395


In [22]:
print(model.predict([sample]))

[1]


In [23]:
#mutinomial

In [25]:

model = LogisticRegression(multi_class='multinomial', max_iter=200)
model.fit(x, y)


C:\Users\ASUS\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=200, multi_class='multinomial')

In [26]:
model.coef_

array([[-0.4248362 ,  0.96741615, -2.51536487, -1.08235714],
       [ 0.53512448, -0.32086871, -0.20703587, -0.94315282],
       [-0.11028828, -0.64654745,  2.72240073,  2.02550996]])

In [27]:
model.intercept_

array([  9.85393186,   2.23224793, -12.08617979])

In [28]:
sample=[1.5,.8,3.5,.9]
z0=-0.4248362*1.5+ 0.96741615*.8+-2.51536487*3.5+-1.08235714*.9+9.85393186
z1=0.53512448*1.5+-0.32086871*.8+-0.20703587*3.5+-0.94315282*.9+ 2.23224793
z2=-0.11028828*1.5+-0.64654745*.8+ 2.72240073*3.5+2.02550996*.9+-12.08617979
print(z0,z1,z2)

0.21271200899999876 1.2047765990000001 -1.4174886509999993


In [29]:
model.decision_function([sample])

array([[ 0.21271201,  1.20477663, -1.41748864]])

In [30]:
p0=np.exp(z0)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
p1=np.exp(z1)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
p2=np.exp(z2)/(np.exp(z0)+np.exp(z1)+np.exp(z2))
print(p0,p1,p2)

0.2568919769085897 0.6927853862125806 0.05032263687882975


In [31]:
model.predict_proba([sample])

array([[0.25689197, 0.69278539, 0.05032264]])

In [32]:
model.predict([sample])

array([1])