In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
iris=load_iris()

In [3]:
x=iris.data
y=iris.target

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [5]:
sc=StandardScaler()
x_train_std=sc.fit_transform(x_train)
x_test_std=sc.transform(x_test)

In [6]:
x_train_std

array([[-1.02366372, -2.37846268, -0.18295039, -0.29318114],
       [ 0.69517462, -0.10190314,  0.93066067,  0.7372463 ],
       [ 0.92435306,  0.58106472,  1.04202177,  1.63887031],
       [ 0.1222285 , -1.92315077,  0.6522579 ,  0.35083601],
       [ 0.92435306, -1.24018291,  1.09770233,  0.7372463 ],
       [-0.33612839, -1.24018291,  0.03977182, -0.16437771],
       [ 2.07024529, -0.10190314,  1.26474398,  1.38126345],
       [ 0.46599617,  0.58106472,  0.48521625,  0.47963944],
       [-0.45071761, -1.46783886, -0.01590873, -0.16437771],
       [ 0.46599617, -0.784871  ,  0.59657735,  0.7372463 ],
       [ 0.46599617, -0.55721505,  0.70793846,  0.35083601],
       [-1.13825295, -1.24018291,  0.37385514,  0.60844287],
       [ 0.46599617, -1.24018291,  0.6522579 ,  0.86604973],
       [ 1.26812073,  0.35340877,  0.48521625,  0.22203258],
       [ 0.69517462, -0.10190314,  0.76361901,  0.99485316],
       [ 0.1222285 ,  0.80872067,  0.37385514,  0.47963944],
       [-1.25284217,  0.

In [7]:
x_test_std

array([[-0.10694994, -0.55721505,  0.70793846,  1.51006688],
       [ 0.1222285 , -1.92315077,  0.09545238, -0.29318114],
       [-0.45071761,  2.6299683 , -1.35224199, -1.32360858],
       [ 1.6118884 , -0.32955909,  1.37610509,  0.7372463 ],
       [-1.02366372,  0.80872067, -1.29656144, -1.32360858],
       [ 0.46599617,  0.58106472,  1.20906343,  1.63887031],
       [-1.02366372,  1.03637663, -1.40792255, -1.19480515],
       [ 0.92435306,  0.12575281,  0.48521625,  0.35083601],
       [ 1.03894229, -0.55721505,  0.5408968 ,  0.22203258],
       [ 0.23681773, -0.55721505,  0.09545238,  0.09322915],
       [ 0.23681773, -1.01252695,  0.98634122,  0.22203258],
       [ 0.5805854 ,  0.35340877,  0.37385514,  0.35083601],
       [ 0.23681773, -0.55721505,  0.48521625, -0.03557428],
       [ 0.69517462, -0.55721505,  0.42953569,  0.35083601],
       [ 0.23681773, -0.32955909,  0.48521625,  0.22203258],
       [-1.13825295,  1.26403258, -1.35224199, -1.45241201],
       [ 0.1222285 , -0.

In [18]:
svm=SVC(kernel='poly',random_state=0,gamma=10,C=10)

In [19]:
svm.fit(x_train_std,y_train)

SVC(C=10, gamma=10, kernel='poly', random_state=0)

In [20]:
y_pred=svm.predict(x_test_std)

In [21]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0])

In [22]:
print('wrong prediction out of total ')
print((y_test!=y_pred).sum(),'/',((y_test==y_pred).sum()+(y_test!=y_pred).sum()))

wrong prediction out of total 
1 / 45


In [23]:
print('percentage accuracy',100*accuracy_score(y_test,y_pred))

percentage accuracy 97.77777777777777


In [24]:
from sklearn.metrics import confusion_matrix
c_m=confusion_matrix(y_test,y_pred)
c_m

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [25]:
import numpy as np
np.where(y_pred!=y_test)

(array([37]),)

In [26]:
y_pred[37]

np.int64(2)

In [27]:
y_test[37]

np.int64(1)